apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-scanner.configMapName" . }}
  labels:
    {{- include "k8s-scanner.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  RF_ENDPOINT: {{ .Values.global.rf_root_url }}
