# Default values for k8s-scanner.
# This is a YAML-formatted file.

global:
  rf_app_host: "https://frontrow.rapidfort.com"

secret:
  rf_access_id: ""
  rf_secret_access_key: ""

image:
  repository: rapidfort/k8s-scanner
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

clusterRole:
  create: true
  annotations: {}

serviceAccount:
  create: true
  annotations: {}

clusterRoleBinding:
  create: true
  annotations: {}

secret: {}

configMap: {}

podAnnotations: {}

resources: {}

capAddSysPtrace:
  enabled: false
