# Default values for k8s-scanner.
# This is a YAML-formatted file.

global:
  rf_app_host: "frontrow.rapidfort.com"

secret:
  rf_access_id: ""
  rf_secret_access_key: ""

image:
  repository: 274057717848.dkr.ecr.us-east-1.amazonaws.com/k8s-scanner
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

clusterRole:
  create: true
  annotations: {}

serviceAccount:
  create: true
  annotations: {}

clusterRoleBinding:
  create: true
  annotations: {}

secret: {}

configMap: {}

podAnnotations: {}

resources: {}
